Portfolio finish mobile version
gdvl777/Portfolio-finish-mobile-version pull request #11
Opened 2023-04-28 22:23 UTC by gdvl777

build the middle section of the mobile website.

2023-04-28 23:17 UTC, Eternalgratis requested changes
# Status: Required Changes ♻️
Hi @gdvl777 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights
✅ You used the correct GitHub flow
✅ Descriptive pull request message
✅ Linter error checks validated


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 23:17 UTC, Eternalgratis commented on README.md
## [Required changes]
- For professionalism purposes, kindly consider removing the live demo section for now and adding it back when your project requires it in the nearest future.
- There are still a couple of links in your README that are broken, it doesn't lead the user anywhere when it's being clicked on. Kindly fix these and consider customizing them accordingly.🙂

2023-04-28 23:17 UTC, Eternalgratis commented on src/index.html
> +            <nav class="nav-item2"></nav>
## [Required changes]
- For semantics and convention purposes, please consider removing the nav tag wrapped around your logo. The a tag will do just fine.
- Kindly remove the nav tag with the class name "nav-item1" if you are not using it. This is in order to maintain a clean code .

2023-04-28 23:17 UTC, Eternalgratis commented on src/index.html
> +        </nav>
## [Optional changes]
- Kindly consider removing this part of your code since your current project doesn't require that feature yet.

2023-04-28 23:17 UTC, Eternalgratis commented on src/index.html
> +            </form>
## [Optional changes]
- You might please want to consider removing this section of your project as it isn't in the requirement. It is always good to maintain a clean code

2023-04-28 23:17 UTC, Eternalgratis commented on src/styles.css
> +
## [Optional changes]
- Kindly remove every commented code. This is to ensure and maintain a clean code base

2023-04-28 23:17 UTC, Eternalgratis commented on src/styles.css
> +}
## [Required changes]
- The position of the subtitle "Let's connect" is currently not the same as the Figma design. Kindly fix it

Figma Design
![image](https://user-images.githubusercontent.com/89091822/235268152-9fec127f-ccd2-46b1-8cdf-6b310f4e46e3.png)


Your Design
![image](https://user-images.githubusercontent.com/89091822/235268067-fad24f8d-87b4-4a06-a036-8503c44cb17a.png)

2023-04-30 02:10 UTC, didierganthier requested changes
Hi @gdvl777 ,

🎉 Great job on addressing the feedback from the previous review! You've made some solid progress in implementing the requested changes. However, there are still a few areas that need some attention before we can move on to the next project.

<img src="https://media.giphy.com/media/e56n4Z0mmkxZS/giphy.gif" />

## Highlights
- Designed Cards ✔️ 
- Added Linters checks ✔️ 
- Followed GitHub flow ✔️ 

## Required Changes 🛠
- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-04-30 02:10 UTC, didierganthier commented on src/index.html
> +            </ul>
[OPTIONAL] Well done so far 💯 but consider adjusting the design issue present here. Take a look 👇🏽 

## Your design

![Screenshot 2023-04-29 at 21 36 43](https://user-images.githubusercontent.com/45739963/235331389-31bc0dde-5ac6-43fc-a694-d505b418d8bd.png)

## Figma

![Screenshot 2023-04-29 at 21 36 59](https://user-images.githubusercontent.com/45739963/235331395-1e1761cd-1024-4dac-ad48-4652d5c433fe.png)

This is only optional because it was not mentioned by the previous reviewer but please consider implementing it as it's necessary to have a good-looking app with no designs fault. 🎨

2023-04-30 02:10 UTC, didierganthier commented on src/main.js
> +    </div>
[OPTIONAL] Hey 👋🏽  consider adjusting the design, it does not have the right margins to match the Figma 👇🏽 

## Your design

![Screenshot 2023-04-29 at 21 45 05](https://user-images.githubusercontent.com/45739963/235331824-c1921f17-0f25-4ff4-9d8e-70c03d914e25.png)
## Figma

![Screenshot 2023-04-29 at 21 55 24](https://user-images.githubusercontent.com/45739963/235331832-76983cba-2ab9-44cf-a1eb-21e719aa3ed8.png)

This is only optional because it was not mentioned by the previous reviewer but please consider implementing it as it's necessary to have a good-looking app with no designs fault. 🎨

2023-04-30 02:10 UTC, didierganthier commented on README.md
>  - [💻 Getting Started](#getting-started)
Nice README 💯 but seems like some sections were removed in the `Getting Started` part 👀 some may be removed as they are not relevant to the project for now but some others such as `Setup`, `Prerequisites` and `Install` should be there.

2023-04-30 02:41 UTC, Efiamotu-1 approved these changes
Hi @gdvl777 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif)


## Highlights :dart: 
* Correct GitHub flow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-30 02:41 UTC, Efiamotu-1 commented on src/index.html
- [ ] please make sure to remove the excess space between the paragraoh and social media icons which you currently have in your design. it is inconsistent with the figma template and as such please correct it. :+1: 
- figma design
![p-mi](https://user-images.githubusercontent.com/89055502/235332895-7a88a688-89ef-416f-acbc-ed2384fe616c.png)
- your design
![s-pmi](https://user-images.githubusercontent.com/89055502/235332904-23dd93af-0d75-41a9-9441-21102ee7fe79.png)

2023-04-30 02:41 UTC, Efiamotu-1 commented on src/index.html
[OPTIONAL]
- [ ] It is also important to use good PR title and summary when making a pull request attached below is an image of how your pr title and summary for this project should look like please make sure to make the correct changes before resubmitting for a new pull request. :+1: 
![good-pr](https://user-images.githubusercontent.com/89055502/234389170-2ece21cc-1ad3-46e1-8e31-cb39f5f8304d.png)

2023-05-01 20:26 UTC, closed without merging